### PR TITLE
GH-120 Command + Args abstraction

### PR DESCRIPTION
**Pull request by jmfayard**
### Checklist
- [x] I've read the [guide for contributing](https://github.com/lordcodes/turtle/blob/master/CONTRIBUTING.md).
- [x] I've checked there are no other [open pull requests](https://github.com/lordcodes/turtle/pulls) for the same change.
- [x] I've formatted all code changes with `./gradlew lcCodeFormat`.
- [x] I've ran all checks with `./gradlew lcChecks`.
- [ ] I've updated documentation if needed.
- [x] I've added or updated tests for changes.

### Description

> **Update:** Neither complete nor up-to-date. The real documentation is inside the unit tests

Creating commands

```kotlin
// the unreadable way
val lsCommand = Command("ls", Args(listOf("-a", "-l", "--color=when", "src", "build")))

// better
val folders = Args("src", "build")
val options = Args("-l", "-a", ""--color=when")
val lsComand = Command("ls") + options + folders
```

Executing commands

```kotlin
val helloWorld = Command("echo", Args("hello", "world")..executeOrThrow()
println(helloWorld)

val invalidCommand = Command("ls", Args("/invalid/path"))
invalidCommand.executeOrElse {
  println("Invalid path, got expection $it, quick return instead of crashing")
  return
}
```

### CODE REVIEW

**Comment by jmfayard** [comment]
@lordcodes I think I'm done extracting the `Command` (+`Args`) part of  https://github.com/lordcodes/turtle/pull/122
What do you think?

**Comment by lordcodes** [comment]
Thanks. I still don't understand all the arguments logic, I don't see why a List of Any is better as an API than a List of String which is actually what the shell needs. It results on tons of logic for checking, handling all the different types user could magically know to provide.

Will need to read in more detail, should have time in a few days.

**Comment by jmfayard** [comment]
@lordcodes 

>  I'm not sure I understand why a List of 'Any' is better as an API than a List of String which is actually what the shell needs.

It's now a proper type `Args` (or `YourType: WithArg`), not a list of any.

Args handle in a convenient way common types that are present in the JDK. 
`WithArg` is an interface for the types you define on your own (not in the JDK or in the library).

Args is better than `String` (primitive obsession which is a major sin of Bash programming) because

- there are tons of strings in any given program that are not supposed to be used as a command-line argument
- there are tons of non-String values that could be used as a command-line argument like `val options = mapOf("--max" to 12, "--verbose" to true)`

I added operators that makes it as convenient to use `Args` as `String`, check the unit tests.

> a List of String which is actually what the shell needs

For the same reason we don't use GOTO everywhere, even if that's the only thing the processor needs down there. That prevents plenty of occasions to shoot yourself in the foot.

**Comment by lordcodes** [comment]
@jmfayard I have been through and reviewed it, I will finish it off later/tomorrow. Just wanted to let you know, so you know that I am 'on it'! ☺️

Thanks for your changes, I am starting to see why you wanted to make these changes, really cool!

**Comment by jmfayard** [comment]
Pretty happy with the last commit. I made `Executable` open which means you can do `object Git : Executable("git") { }` and add cool command builders :)

**Comment by lordcodes** [comment]
@jmfayard Thank you for putting all the effort in you have discussing and making these changes. They are a fantastic addition to Turtle. I am planning to re-work all of the built-in commands to use the 'Command' structure internally and re-work how the commands are grouped to work like the 'Git' sample.

**Comment by jmfayard** [comment]
@lordcodes hurrah, thanks a lot!

**Comment by lordcodes** [comment]
I will probably have a look at using the Command abstraction to build the built-in commands and then will get a new version of Turtle out soon with it included.

**Comment by jmfayard** [comment]
your changes make sense

except one: I think I still like better

```
object Git : Executable("git") {

}
```

which you can use elsewhere as `command(Git, "something", "something")`

than the pattern object + executable

```
object Git {
   val executable = Executable("git", URL("https://git-scm.com/docs"))
}
```

`command(Git.executable, "something", "something")`

but I guess you will find out when you reimplement the built-in commands

**Comment by lordcodes** [comment]
Potentially we will see if I start to think the same thing. I just really don't like the idea of making it open and being unable to make Executable a data class.

However, I take your point on board, I will see if there is a balance between the two.

**Pull request merged**
